# Generated by Django 5.1.15 on 2026-05-28 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('referrals', '0001_initial'),
        ('transactions', '0003_remove_transaction_tx_unique_hash_when_set_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='invited_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_as_invited', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referral',
            name='inviter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_as_inviter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referralmilestonereward',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='milestone_rewards', to='transactions.transaction'),
        ),
        migrations.AddField(
            model_name='referralmilestonereward',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_milestones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['inviter', 'level'], name='referrals_r_inviter_7c5c03_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['invited_user', 'level'], name='referrals_r_invited_f6ff00_idx'),
        ),
        migrations.AddConstraint(
            model_name='referral',
            constraint=models.UniqueConstraint(fields=('inviter', 'invited_user', 'level'), name='unique_inviter_invited_level'),
        ),
        migrations.AddIndex(
            model_name='referralmilestonereward',
            index=models.Index(fields=['user', '-awarded_at'], name='referrals_r_user_id_15b3bf_idx'),
        ),
        migrations.AddConstraint(
            model_name='referralmilestonereward',
            constraint=models.UniqueConstraint(fields=('user', 'milestone'), name='unique_user_milestone'),
        ),
    ]
