# === FILE: backend/wallet/migrations/0002_rename_...py ===
"""No-op migration.

Originally autogenerated to reconcile index/PK naming differences
between a hand-written 0001_initial and the model state. The
0001_initial has since been brought into line with autogen so this
file is a no-op kept only for deployments that already applied it.
"""
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0001_initial"),
    ]

    operations = []
