# Generated by Django 5.1.15 on 2026-05-28 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('code', models.CharField(help_text='ISO 3166-1 alpha-2', max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('flag_emoji', models.CharField(blank=True, max_length=8)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PlatformConfig',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('value', models.JSONField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DialCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='e.g. +98', max_length=8)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dial_codes', to='reference.country')),
            ],
            options={
                'ordering': ['country__name'],
            },
        ),
    ]
