# Generated by Django 5.1.15 on 2026-05-28 12:41

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='Season', max_length=64)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='RewardCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ends_at', models.DateTimeField()),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('reward_amount_hcoin', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=18)),
                ('status', models.CharField(choices=[('active', 'Active'), ('claimable', 'Claimable'), ('claimed', 'Claimed'), ('expired', 'Expired')], default='active', max_length=16)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
