# Generated by Django 5.1.15 on 2026-05-28 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rewards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardcycle',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_cycles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='rewardcycle',
            index=models.Index(fields=['user', 'status'], name='rewards_rew_user_id_b798db_idx'),
        ),
        migrations.AddIndex(
            model_name='rewardcycle',
            index=models.Index(fields=['status', 'ends_at'], name='rewards_rew_status_aa2425_idx'),
        ),
    ]
