# Generated by Django 5.1.15 on 2026-05-28 12:41

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0002_gateway_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bot_type', models.CharField(choices=[('basic', 'Basic Bot Trader'), ('expert', 'Expert Bot Trader')], max_length=16)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='active', max_length=16)),
                ('balance_at_start_hcoin', models.DecimalField(decimal_places=8, default=Decimal('0'), help_text="User's H Coin balance immediately before fee deduction.", max_digits=18)),
                ('fee_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fee_amount_hcoin', models.DecimalField(decimal_places=8, max_digits=18)),
                ('duration_seconds', models.IntegerField()),
                ('profit_min_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('profit_max_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('profit_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('profit_amount_hcoin', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completes_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('fee_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='transactions.transaction')),
                ('profit_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='transactions.transaction')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
