# Generated by Django 5.1.15 on 2026-05-28 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trade', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='botsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='botsession',
            index=models.Index(fields=['user', '-started_at'], name='trade_botse_user_id_9a0840_idx'),
        ),
        migrations.AddIndex(
            model_name='botsession',
            index=models.Index(fields=['status', 'completes_at'], name='trade_botse_status_218eb4_idx'),
        ),
        migrations.AddConstraint(
            model_name='botsession',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('user',), name='unique_active_bot_per_user'),
        ),
    ]
