# === FILE: backend/transactions/migrations/0003_remove_transaction_tx_unique_hash_when_set_and_more.py ===
"""No-op migration.

Originally autogenerated by Django to reconcile cosmetic differences
between an earlier hand-written 0001_initial and the model state. The
0001_initial has since been rewritten to match autogen exactly so
this file no longer needs to do anything — kept as a no-op so existing
deployments that already applied it stay consistent.
"""
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0002_gateway_fields"),
    ]

    operations = []
