# Generated by Django 5.1.15 on 2026-05-28 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('deposit_init', 'Deposit initiated'), ('deposit_complete', 'Deposit completed'), ('withdraw_init', 'Withdrawal initiated'), ('withdraw_approve', 'Withdrawal approved'), ('withdraw_complete', 'Withdrawal completed'), ('reward_claim', 'Reward claimed'), ('commission_pay', 'Commission paid'), ('registration', 'User registered'), ('login', 'User login'), ('password_change', 'Password change')], max_length=64)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
